### ISSUE TITLE
How to open file and use it

### ISSUE THREAD

**Issue by ArthurDZYA** [triippz-tech/JYTB#14]
i dont know how to open file and use it. Im using kali linux. Im new to all this ion understand lot of things sooo. thats why i ask this question

**Comment by kingsmanlab** [comment]
@ArthurDZYA check new update on 
https://github.com/triippz-tech/JYTB/tree/JYTB-Linux-Firefox

**Comment by ArthurDZYA** [comment]
this link doesnt work

чт, 14 мая 2020 г., 21:44 h4ckm3-id <notifications@github.com>:

**Comment by ArthurDZYA** [comment]
also i checked your profile and you dont have update

чт, 14 мая 2020 г., 21:44 h4ckm3-id <notifications@github.com>:

**Comment by ArthurDZYA** [comment]
maybe you hacked me

чт, 14 мая 2020 г., 21:44 h4ckm3-id <notifications@github.com>:

**Comment by kingsmanlab** [comment]
LOL @ArthurDZYA 
https://github.com/triippz-tech/JYTB/tree/JYTB-Linux-Firefox

**Comment by ArthurDZYA** [comment]
Thank you. I just want to go big with mu music

пт, 15 мая 2020 г., 0:47 h4ckm3-id <notifications@github.com>:

**Comment by ArthurDZYA** [comment]
i get this error everytime
Exception in thread "main" org.openqa.selenium.WebDriverException:
java.net.ConnectException: Failed to connect to
localhost/0:0:0:0:0:0:0:1:12823
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'kali', ip: '127.0.1.1', os.name: 'Linux', os.arch:
'i386', os.version: '4.19.0-kali4-686-pae', java.version: '11.0.3'
Driver info: driver.version: FirefoxDriver
at
org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92)
at
org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at
org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
at
org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:147)
at com.services.BotWorker.setFirefoxDriver(BotWorker.java:163)
at com.services.BotWorker.initializeBotFree(BotWorker.java:104)
at com.services.BotWorker.<init>(BotWorker.java:86)
at com.App.main(App.java:86)
Caused by: java.net.ConnectException: Failed to connect to
localhost/0:0:0:0:0:0:0:1:12823
at
okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
at
okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165)
at
okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
at
okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
at
okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
at
okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
at
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at
okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
at
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at
okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
at
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
at okhttp3.RealCall.execute(RealCall.java:77)
at
org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
at
org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:105)
at
org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
at
org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
at
org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
... 8 more
Caused by: java.net.ConnectException: Connection refused (Connection
refused)
at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
at
java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
at
java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
at
java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
at java.base/java.net.Socket.connect(Socket.java:591)
at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
at
okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245)
... 30 more

пт, 15 мая 2020 г. в 00:47, h4ckm3-id <notifications@github.com>:

**Comment by ArthurDZYA** [comment]
and also where is full version?

пт, 15 мая 2020 г. в 00:47, h4ckm3-id <notifications@github.com>:

**Comment by kingsmanlab** [comment]
@ArthurDZYA join here https://discord.gg/6Ax2Qbe
