### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by OpiumCity** [triippz-tech/JYTB#9]
When I run the app file, I've got this :
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/<myusername>/Downloads/JYTB-patch-1/target/classes/userAgents/CHROME.txt
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at com.triippztech.app.utils.UserAgent.<init>(UserAgent.java:38)
	at com.triippztech.app.services.BotWorker.initializeBot(BotWorker.java:83)
	at com.triippztech.app.services.BotWorker.<init>(BotWorker.java:76)
	at com.triippztech.app.App.main(App.java:79)

**Comment by sauravdudeja** [comment]
UserAgent.java -> replace constuctor 

` public UserAgent(Driver driverType) throws IOException {
        String path1 = Objects.requireNonNull(getClass().getClassLoader().getResource(
            "userAgents/" + driverType.toString() + ".txt")).getPath();
        path1 = path1.replaceFirst("/","");
        Path path = Paths.get(path1);
        this.userAgentList = Files.readAllLines(path);
    }`

**Comment by kingsmanlab** [comment]
Check new update on 
[https://github.com/triippz-tech/JYTB/tree/JYTB-Linux-Firefox](url)

**Comment by prodbyhtwo** [comment]
Hey, I am trying to install selenium and use this script but I can't get it to work. please help, will pay for someone to teach me
